//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasTakipSistemi.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentUserData
    {
        public Nullable<int> currentUserRoleID { get; set; }
        public string currentUserName { get; set; }
        public Nullable<int> userID { get; set; }
        public int ID { get; set; }
    }
}
