//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasTakipSistemi.Models.DataModel
{
    
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductSerialNumber { get; set; }
        public int CategoryID { get; set; }
        public string ProductBrand { get; set; }
        public int PersonID { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public int ProductAmount { get; set; }
        public System.DateTime ProductWarrantyDate { get; set; }
        public string ServiceContact { get; set; }
        public string ProductFeatures { get; set; }
        public string ProductImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Person Person { get; set; }
    }
}
